# Generated by Django 4.1.2 on 2022-10-21 07:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='caption')),
                ('tags', models.CharField(blank=True, max_length=150, verbose_name='tags')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='last update date and time')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=13, unique=True, verbose_name='phone number')),
                ('is_owner', models.BooleanField(default=False, verbose_name='admin status')),
                ('order', models.PositiveIntegerField(default=0)),
                ('favourite_posts', models.ManyToManyField(blank=True, default=None, to='PhotographyProfile.post', verbose_name='favourite posts')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['order'],
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='comment text')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='last update date and time')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PhotographyProfile.comment', verbose_name='this comment is a reply to a comment...')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotographyProfile.post', verbose_name='post that the comment is related to')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PhotographyProfile.user', verbose_name='user that left the comment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
                'ordering': ['order'],
            },
        ),
    ]
